#page title
app_name                           : minim
app_description                    : Rethinking what a chat app means.
github_link                        : https://github.com/MichaelSafwatHanna/minim
app_icon                           : https://raw.githubusercontent.com/MichaelSafwatHanna/minim/master/app/src/main/ic_launcher-web.png
enable_smart_app_banner            : true



# Feature List
features                           :

  - title                          : Minimal Design
    description                    : Designed to be used as little as possible by cutting off the overwhelming features.
    icon                           : square
    
  - title                          : Fully Encrypted
    description                    : Messages are encrypted using Advanced Encryption Standard with a shared private key.
    icon                           : lock

  - title                          : Phone Authentication
    description                    : No more forgetting about your password, all what you need is your phone number.
    icon                           : phone

  - title                          : Auto-destructive Messages
    description                    : We help you move on and let go of the past by destructing messages after 24 hours maximum.
    icon                           : clock

  - title                          : Nonaddictive Messages
    description                    : Messages are limited to 120 characters, made to be informative not addictive.
    icon                           : syringe
  
  - title                          : Email Attachments
    description                    : Going back to basics, isn't that what email was really made for?
    icon                           : envelope
  
  - title                          : Free & Without Ads
    description                    : Annoying ads only exist in other apps, not ours. Once you go minimal, you can never go back.
    icon                           : dollar-sign

  - title                          : Open Source
    description                    : Source code is shared on GitHub, open for contributions. We have nothing to hide.
    icon                           : code-branch
  
  - title                          : Made with Love
    description                    : Encourages you to spend quality time doing the things you love the most, free of distraction.
    icon                           : heart


# Theme Settings
topbar_color                       : "#000000"
topbar_transparency                : 0.1
topbar_title_color                 : "#ffffff"

cover_image                        : https://66.media.tumblr.com/a4894c9cbf914fe616789dd91aab4fee/tumblr_o33vcw2dBO1u1rcako1_1280.jpg
cover_overlay_color                : "#000000"
cover_overlay_transparency         : 0.7

device_color                       : black

body_background_color              : "#000000"

link_color                         : "#1d63ea"

app_title_color                    : "#ffffff"
app_price_color                    : "#ffffff"
app_description_color              : "#ffffff"

feature_title_color                : "#ffffff"
feature_text_color                 : "#eeeeee"

feature_icons_foreground_color     : "#000000"
feature_icons_background_color     : "#ffffff"